### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by gaamplatform** [carliv/carliv_touch_recovery_new#1]
When i'm trying to build this recovery (cm13) for LG G2 Mini (g2m) i'm getting this error:
`build/core/base_rules.mk:157: *** external/busybox: MODULE.TARGET.STATIC_LIBRARIES.libclearsilverregex already defined by bootable/recovery/busybox. Stop.`

**Comment by carliv** [comment]
Did you added busybox in cm13? the official repo doesn't has it:

`<project path="external/apache-http" name="CyanogenMod/android_external_apache-http" groups="pdk" />
  <project path="external/bash" name="CyanogenMod/android_external_bash" />
  <project path="external/boringssl" name="CyanogenMod/android_external_boringssl" groups="pdk" />
  <project path="external/bouncycastle" name="CyanogenMod/android_external_bouncycastle" groups="pdk" />
  <project path="external/brctl" name="CyanogenMod/android_external_brctl" />
  <project path="external/bzip2" name="CyanogenMod/android_external_bzip2" groups="pdk" />
<project path="external/connectivity" name="CyanogenMod/android_external_connectivity" />`

 If you did add it manually, then you need to modify few things in recovery or to move that folder somewhere else until you build it. I'm sorry I can't provide two versions yet, one for those who use cm-13 as it is and one for those who manually patch it. I'm busy right now working to activate the f2fs, exfat and ntfs support (it's builtin but not active yet). Maybe after I'll finish next update I'll add a version without busybox.

**Comment by gaamplatform** [comment]
I forgot that. The busybox was added by an unofficial LG L5 manifest that i'm using. I removed it and the recovery builds.
